---
- hosts: all
  vars_prompt:
    - name: 'username'
      prompt: 'Enter username for the new user'
      private: no

    - name: 'password'
      prompt: 'Enter password for the new user'
      private: yes
      encrypt: sha512_crypt
      confirm: yes

  roles:
    - anu
