---
- name: Create new user and add to the "sudo" group
  user:
    name: "{{ username }}"
    password: "{{ password }}"
    groups: sudo
    shell: /bin/bash

- name: Copy over SSH authorized_keys file to new user
  template:
    src: authorized_keys.j2
    dest: "{{ ansible_env.HOME }}/.ssh/authorized_keys"
    mode: '0600'
    owner: "{{ username }}"
    group: "{{ username }}"
