---
- name: Create new user and add to the "sudo" group
  user:
    name: "{{ username }}"
    password: "{{ password }}"
    groups: sudo
    shell: /bin/bash

- name: Ensures .ssh dir exists
  file:
    path: "/home/{{ username }}/.ssh"
    state: directory

- name: Copy over SSH authorized_keys file to new user
  template:
    src: authorized_keys.j2
    dest: "/home/{{ username }}/.ssh/authorized_keys"
    mode: '0600'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Allow user to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^{{ username }}'
    line: '{{ username }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
