---
- name: Install GitLab Runner
  shell: |
    curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash
    sudo apt install gitlab-runner

- name: "Configure GitLab Runner: Coordinator URL"
  pause:
    prompt: "Enter the GitLab coordinator URL"
  register: coordinator_url

- name: "Configure GitLab Runner: Registration token"
  pause:
    prompt: "Enter the GitLab registration token"
    echo: no
  register: registration_token

- name: "Configure GitLab Runner: Description"
  pause:
    prompt: "Enter the description for this runner"
  register: description

- name: Install GitLab Runner
  shell: >
    gitlab-runner register
    --non-interactive
    --url "{{ coordinator_url }}"
    --registration-token "{{ registration_token }}"
    --description "{{ description }}"
    {% if gitlab_runner_purpose == 'cd' %}
    --executor shell
    {% endif %}
    {% if gitlab_runner_purpose == 'ci' %}
    --executor docker
    {% endif %}
  become: yes

- name: Allow gitlab-runner user to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^gitlab-runner'
    line: 'gitlab-runner ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
